### ISSUE TITLE
Postgresql Instrumentation Support

### ISSUE THREAD

**Issue by jonmchan** [signalfx/signalfx-ruby-tracing#20]
Does signalFX have any postgresql instrumentation support for Ruby? I don't see it in the list. Thanks.

**Comment by rmfitzpatrick** [comment]
We largely source and provide library instrumentations from the [OpenTracing contributions project](https://github.com/opentracing-contrib?utf8=%E2%9C%93&q=&type=&language=ruby), which is currently without a postgres offering.  Contributing an instrumentation, or sourcing if one becomes available, and adding a corresponding instrumentor would be ideal for this project.

**Comment by rmfitzpatrick** [comment]
We have offered pg >= 0.18.0 since 1.3.0 using https://github.com/signalfx/ruby-pg-instrumentation.
