### ISSUE TITLE
Faraday instrumentation is setting span tag error to true for status code < 500

### ISSUE THREAD

**Issue by Joas1988** [signalfx/signalfx-ruby-tracing#46]
In https://github.com/signalfx/ruby-faraday-tracer/commit/16fa7daeea1a8abcce579e31f87efd174a55f9ec @owais removed condition for status code and that's causing every request being marked as error.

**Comment by jtmalinowski** [comment]
Hi @Joas1988, I created an internal ticket for this as well. I'll let you know as soon as we have something.

**Comment by Joas1988** [comment]
Resolved by https://github.com/signalfx/ruby-faraday-tracer/commit/11dc8a5a26556c777e220b83d61cb17e3b6acac7, so closing.
